[package]
name = "recip"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
# orion_dl = { git = "https://github.com/gizatechxyz/orion", rev = "5ed236784d3c7add2385b7c7bee394070a445130" }
# orion_numbers = { git = "https://github.com/gizatechxyz/orion", rev = "5ed236784d3c7add2385b7c7bee394070a445130" }

orion_dl = { path = "/Users/raphaeldoukhan/Desktop/Giza/Frameworks/orion" }
orion_numbers = { path = "/Users/raphaeldoukhan/Desktop/Giza/Frameworks/orion" }


[dev-dependencies]
cairo_test = "2.7.0"

[cairo]
enable-gas = false
